[package]
name = "grepr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
regex = "1.10.5"
sys-info = "0.9.1"
walkdir = "2.5.0"

[dev-dependencies]
anyhow = "1.0.86"
assert_cmd = "2.0.14"
predicates = "3.1.0"
pretty_assertions = "1.4.0"
rand = "0.8.5"
